version: "3"
services: 
  infinity-chat-db:
    image: mysql:latest
    networks: 
      intern:
        ipv4_address: 172.20.0.2
    container_name: "InfinityChat-db"
    environment:
      - "MYSQL_ROOT_PASSWORD=sml12345"
    ports:
      - "3306:3306"
  razor:
    build: 
      context: "./"
      dockerfile: "./Dockerfile"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
    networks:
      intern:
        ipv4_address: 172.20.0.3
      extern:
        
    ports:
      - "80:80"
      - "443:443"

networks:
  intern:
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
  extern:
    driver: bridge