version: "3"
services: 
  infinity-chat-db:
    image: mysql:latest
    networks: 
      intern:
        ipv4_address: 172.20.0.2
    container_name: "InfinityChat-db"
    environment:
      - "MYSQL_ROOT_PASSWORD=sml12345"
    ports:
      - "3306:3306"
    # This healthcheck exists because the mysql db needs to be accessible for the ef migration. 
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psml12345" ]
      interval: 5s
      timeout: 2s
      retries: 4
  blazor:
    build: 
      context: "./"
      dockerfile: "./Dockerfile"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
    networks:
      intern:
        ipv4_address: 172.20.0.3
      extern:
        
    ports:
      - "80:80"
    depends_on:
      infinity-chat-db:
        condition: service_healthy

networks:
  intern:
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
  extern:
    driver: bridge